name: Ecolodge Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pgsql

      - name: Install Composer Dependencies
        env:
            DB_CONNECTION: pgsql
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: 6543
            DB_DATABASE: ${{ secrets.DB_DATABASE }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM Dependencies
        run: npm install

      - name: Build NPM Assets
        run: npm run build

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.sshuser
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.sshuser/id_user
          chmod 600 ~/.sshuser/id_user
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Synchronize Files to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.VPS_HOST }}
          REMOTE_USER: ${{ secrets.VPS_USER }}
          TARGET: "/var/www/html/ecolodgesmr"
          SSH_KEY_PATH: "~/.sshuser/id_user"  # Correct path to your private key

      - name: Run Remote/Artisan Commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: "~/.sshuser/id_user"  # Correct path to your private key
          script: |
            cd /var/www/html/ecolodgesmr
            php artisan optimize
