name: Ecolodge Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pgsql

      - name: Install Composer Dependencies
        env:
            DB_CONNECTION: pgsql
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: 6543
            DB_DATABASE: ${{ secrets.DB_DATABASE }}
            DB_USERNAME: ${{ secrets.DB_USERNAME }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install NPM Dependencies
        run: npm install

      - name: Build NPM Assets
        run: npm run build

      - name: Synchronize Files to Server (Password-based SSH)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz -e "ssh -p 22" ./ ${VPS_USER}@${VPS_HOST}:/var/www/html/ecolodgesmr

      - name: Run Remote/Artisan Commands
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh ${VPS_USER}@${VPS_HOST} "cd /var/www/html/ecolodgesmr && php artisan optimize"
